volumes:
  {{ cookiecutter.project_slug }}_production_postgres_data: {}
  {{ cookiecutter.project_slug }}_production_postgres_data_backups: {}
  {{ cookiecutter.project_slug }}_production_traefik: {}
  {%- if cookiecutter.cloud_provider == 'None' %}
  {{ cookiecutter.project_slug }}_production_django_media: {}
  {%- endif %}
  {% if cookiecutter.use_celery == 'y' %}
  {{ cookiecutter.project_slug }}_production_redis_data: {}
  {% endif %}


services:
  django:{% if cookiecutter.use_celery == 'y' %} &django{% endif %}
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_django
    {%- if cookiecutter.cloud_provider == 'None' %}
    volumes:
      - {{ cookiecutter.project_slug }}_production_django_media:/app/api/media
    {%- endif %}
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_postgres
    volumes:
      - {{ cookiecutter.project_slug }}_production_postgres_data:/var/lib/postgresql/data
      - {{ cookiecutter.project_slug }}_production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_traefik
    depends_on:
      - django
    volumes:
      - {{ cookiecutter.project_slug }}_production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      {%- if cookiecutter.use_celery == 'y' %}
      - '0.0.0.0:5555:5555'
      {%- endif %}

  redis:
    image: docker.io/redis:6
    {% if cookiecutter.use_celery == 'y' %}
    volumes:
      - {{ cookiecutter.project_slug }}_production_redis_data:/data
    {% endif %}


  {%- if cookiecutter.use_celery == 'y' %}

  celeryworker:
    <<: *django
    image: {{ cookiecutter.project_slug }}_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: {{ cookiecutter.project_slug }}_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: {{ cookiecutter.project_slug }}_production_flower
    command: /start-flower
  {%- endif %}
  {%- if cookiecutter.cloud_provider == 'AWS' %}

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - {{ cookiecutter.project_slug }}_production_postgres_data_backups:/backups:z
  {%- endif %}
  {%- if cookiecutter.cloud_provider == 'None' %}

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_nginx
    depends_on:
      - django
    volumes:
      - {{ cookiecutter.project_slug }}_production_django_media:/usr/share/nginx/media:ro
  {%- endif %}
